name: Docker

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      username:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  docker:
    name: Build image and push to GHRC
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ inputs.username }}
          password: ${{ secrets.token }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.ref_name == 'master' || github.ref_name == 'main' || startsWith(github.ref, 'refs/tags/v') }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ inputs.tag }}
