name: List affected rockspecs

on:
  workflow_call:
    outputs:
      rockspecs:
        value: ${{ jobs.affected.outputs.rockspecs }}

jobs:
  affected:
    name: Find edited rockspecs
    runs-on: ubuntu-22.04
    outputs:
      rockspecs: >-
        ${{
          steps.changed-files.outputs.all_modified_files &&
          format('["{0}"]', steps.changed-files.outputs.all_modified_files) ||
          null
        }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - id: changed-files
        uses: tj-actions/changed-files@v23
        with:
          files: |
            *.rockspec
            rockspecs/*.rockspec
          separator: '", "'
